server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.travel.entity

# JWT配置
jwt:
  secret: your_jwt_secret_key
  expiration: 86400000 # 24小时

logging:
  level:
    com.example.travel: DEBUG
  file:
    name: logs/travel-system.log
